### ISSUE TITLE
Can't find dependencies in node_modules

### ISSUE THREAD

**Issue by inspectordanno** [tranhungt/okcupidjs#30] opened 2018-05-06 22:50 UTC
For some reason the dependencies in node_modules are not working. I have a parent node_modules and there is also another nested node_modules within the okcupidjs folder (not sure if this is intentional). Here are my error messages:

```
cookie.js:32 Uncaught Error: Cannot find module "net"
    at webpackMissingModule (cookie.js:32)
    at Object.<anonymous> (cookie.js:32)
    at __webpack_require__ (bootstrap 518d0c88e6c2b1899e2e:19)
    at Object.<anonymous> (cookies.js:3)
    at __webpack_require__ (bootstrap 518d0c88e6c2b1899e2e:19)
    at Object.<anonymous> (index.js:18)
    at __webpack_require__ (bootstrap 518d0c88e6c2b1899e2e:19)
    at Object.<anonymous> (requester.js:1)
    at __webpack_require__ (bootstrap 518d0c88e6c2b1899e2e:19)
    at Object.<anonymous> (client.js:3)
webpackMissingModule @ cookie.js:32
(anonymous) @ cookie.js:32
__webpack_require__ @ bootstrap 518d0c88e6c2b1899e2e:19
(anonymous) @ cookies.js:3
__webpack_require__ @ bootstrap 518d0c88e6c2b1899e2e:19
(anonymous) @ index.js:18
__webpack_require__ @ bootstrap 518d0c88e6c2b1899e2e:19
(anonymous) @ requester.js:1
__webpack_require__ @ bootstrap 518d0c88e6c2b1899e2e:19
(anonymous) @ client.js:3
__webpack_require__ @ bootstrap 518d0c88e6c2b1899e2e:19
(anonymous) @ index.js:1
__webpack_require__ @ bootstrap 518d0c88e6c2b1899e2e:19
module.exports @ index.js:1
__webpack_require__ @ bootstrap 518d0c88e6c2b1899e2e:19
(anonymous) @ html5-entities.js:190
__webpack_require__ @ bootstrap 518d0c88e6c2b1899e2e:19
(anonymous) @ bootstrap 518d0c88e6c2b1899e2e:62
(anonymous) @ bootstrap 518d0c88e6c2b1899e2e:62
client?cd17:154 [WDS] Errors while compiling. Reload prevented.
msgErrors @ client?cd17:154
onmessage @ socket.js:38
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:883
SockJS._transportMessage @ sockjs.js:881
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2957
client?cd17:157 ./node_modules/okcupidjs/node_modules/request/lib/har.js
Module not found: Error: Can't resolve 'fs' in '/Users/danno/Documents/GitHub/okcupid/node_modules/okcupidjs/node_modules/request/lib'
 @ ./node_modules/okcupidjs/node_modules/request/lib/har.js 3:9-22
 @ ./node_modules/okcupidjs/node_modules/request/request.js
 @ ./node_modules/okcupidjs/node_modules/request/index.js
 @ ./node_modules/okcupidjs/lib/requester.js
 @ ./node_modules/okcupidjs/lib/client.js
 @ ./node_modules/okcupidjs/index.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/index.js ./src/index.html
msgErrors @ client?cd17:157
onmessage @ socket.js:38
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:883
SockJS._transportMessage @ sockjs.js:881
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2957
client?cd17:157 ./node_modules/forever-agent/index.js
Module not found: Error: Can't resolve 'net' in '/Users/danno/Documents/GitHub/okcupid/node_modules/forever-agent'
 @ ./node_modules/forever-agent/index.js 6:10-24
 @ ./node_modules/okcupidjs/node_modules/request/request.js
 @ ./node_modules/okcupidjs/node_modules/request/index.js
 @ ./node_modules/okcupidjs/lib/requester.js
 @ ./node_modules/okcupidjs/lib/client.js
 @ ./node_modules/okcupidjs/index.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/index.js ./src/index.html
msgErrors @ client?cd17:157
onmessage @ socket.js:38
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:883
SockJS._transportMessage @ sockjs.js:881
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2957
client?cd17:157 ./node_modules/okcupidjs/node_modules/tunnel-agent/index.js
Module not found: Error: Can't resolve 'net' in '/Users/danno/Documents/GitHub/okcupid/node_modules/okcupidjs/node_modules/tunnel-agent'
 @ ./node_modules/okcupidjs/node_modules/tunnel-agent/index.js 3:10-24
 @ ./node_modules/okcupidjs/node_modules/request/lib/tunnel.js
 @ ./node_modules/okcupidjs/node_modules/request/request.js
 @ ./node_modules/okcupidjs/node_modules/request/index.js
 @ ./node_modules/okcupidjs/lib/requester.js
 @ ./node_modules/okcupidjs/lib/client.js
 @ ./node_modules/okcupidjs/index.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/index.js ./src/index.html
msgErrors @ client?cd17:157
onmessage @ socket.js:38
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:883
SockJS._transportMessage @ sockjs.js:881
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2957
client?cd17:157 ./node_modules/tough-cookie/lib/cookie.js
Module not found: Error: Can't resolve 'net' in '/Users/danno/Documents/GitHub/okcupid/node_modules/tough-cookie/lib'
 @ ./node_modules/tough-cookie/lib/cookie.js 32:10-24
 @ ./node_modules/okcupidjs/node_modules/request/lib/cookies.js
 @ ./node_modules/okcupidjs/node_modules/request/index.js
 @ ./node_modules/okcupidjs/lib/requester.js
 @ ./node_modules/okcupidjs/lib/client.js
 @ ./node_modules/okcupidjs/index.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/index.js ./src/index.html
msgErrors @ client?cd17:157
onmessage @ socket.js:38
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:883
SockJS._transportMessage @ sockjs.js:881
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2957
client?cd17:157 ./node_modules/forever-agent/index.js
Module not found: Error: Can't resolve 'tls' in '/Users/danno/Documents/GitHub/okcupid/node_modules/forever-agent'
 @ ./node_modules/forever-agent/index.js 7:10-24
 @ ./node_modules/okcupidjs/node_modules/request/request.js
 @ ./node_modules/okcupidjs/node_modules/request/index.js
 @ ./node_modules/okcupidjs/lib/requester.js
 @ ./node_modules/okcupidjs/lib/client.js
 @ ./node_modules/okcupidjs/index.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/index.js ./src/index.html
msgErrors @ client?cd17:157
onmessage @ socket.js:38
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:883
SockJS._transportMessage @ sockjs.js:881
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2957
client?cd17:157 ./node_modules/okcupidjs/node_modules/tunnel-agent/index.js
Module not found: Error: Can't resolve 'tls' in '/Users/danno/Documents/GitHub/okcupid/node_modules/okcupidjs/node_modules/tunnel-agent'
 @ ./node_modules/okcupidjs/node_modules/tunnel-agent/index.js 4:10-24
 @ ./node_modules/okcupidjs/node_modules/request/lib/tunnel.js
 @ ./node_modules/okcupidjs/node_modules/request/request.js
 @ ./node_modules/okcupidjs/node_modules/request/index.js
 @ ./node_modules/okcupidjs/lib/requester.js
 @ ./node_modules/okcupidjs/lib/client.js
 @ ./node_modules/okcupidjs/index.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/index.js ./src/index.html
```

**Comment by inspectordanno** [comment] 2018-05-07 14:49
@xmclark Thanks so much for your help! I'm still a bit new at this, and I really don't too much about node.

I am using a scaffolding, one that I've used for a project before. I forgot to copy the .gitignore file, but I set it up now and the node_modules was removed from git.

The script I was running were `npm i  and the``npm start`. Was I supposed to run `npm run build` as well?

I am running node 8.9.4.

I am going to test it out now with `npm run build` and see if it works. I deleted the nodeexternals and got rid of the` target` which should set it back to `web`.

**Comment by inspectordanno** [comment] 2018-05-11 03:48
@xmclark Thanks, take your time. I'm getting some help with it on my end as well. I really appreciate your help.

**Comment by xmclark** [comment] 2018-05-17 08:14
@inspectordanno So I think the issue is that the `request` library we use is node-only. We need to either switch to a cross-platform library or find a way to fallback on [browser-request](https://github.com/request/request/issues/2834).

WIth that in mind, I don't think using webpack will be very helpful. If you really need this to run in the browser then we just have to wait unfortunately.

**Comment by inspectordanno** [comment] 2018-05-23 17:40
@xmclark Ok, thanks. I did figure out how to use node to do this in the terminal. Thanks for your responses, really appreciate it.

**Comment by xmclark** [comment] 2018-05-23 19:07
@inspectordanno great! While using the API, please keep an eye out for methods that aren’t working correctly. This could mean they don’t return json or maybe they are totally broken. I’ve been petty busy, but there is an ongoing triage because we believe that OKC broke some of the endpoints.

**Comment by inspectordanno** [comment] 2018-05-26 23:39
@xmclark alright. i worked with it a lot and I definitely ran into problems, but I don't really know how to communicate them well :( If you would ever be up for a skype or live coding session, I could definitely show you through that.

**Comment by xmclark** [comment] 2018-09-16 18:09
@inspectordanno hey there, I was trying to revisit this bug, see if a couple months might help :) I assume you might have moved past this now. Though. Let me know if I can help. Otherwise I'm going to close this issue.

**Comment by inspectordanno** [comment] 2018-09-16 20:26
Thanks for getting back!! I used this library with a lot of success, but there were still a lot of times the script crashed for me. This mostly had to do with the filtering. Sometimes when I set the filters a certain way they crashed the script, and also the scripts sometimes would return profiles that didn't fit the parameters I was filtering on. I ended up discarding most of the scripts and using it as a bulk automessenger, and then manually going through my matches/replies afterwards. I'm not sure why this was happening. If you want I could send you the script I was using, although we'd have to make a sample new account to test it out.

**Comment by xmclark** [comment] 2018-09-16 20:28
@inspectordanno yeah post code samples! The simpler the better.

**Comment by inspectordanno** [comment] 2018-09-16 20:36
```
var OKCupid = require('okcupidjs');
var okc = new OKCupid();

//login

okc.login('email@sample.com', 'sample_password', function(err, res, body) {

  var base_query = {
	// Primary filter
	"order_by": "MATCH", // "LOGIN" | "MATCH_AND_DISTANCE" | "ENEMY" | "MATCH"
	"i_want": "women", // "men" {
	"they_want": "men", // "women" | "everyone"
	"minimum_age": 20,
	"maximum_age": 30,
	"radius": 10, // miles from location
	"last_login": 604800, // seconds since last login
  "minimum_height": 61*254,
  "maximum_height": 68*254,
  // "minimum_attractiveness": 2000,
  "bodytype": ["thin", "fit"],
  // "availability": "single",
  "monogamy": "yes",
  "education": ["post_grad", "college_university"],
  "limit": 5
}

	// // Looks filter
	// // Height: each inch is 254
	// // e.g. 5'4  is 5 * 12 * 254  + 4 * 254 = 16256
	// "maximum_height": 61*254,
	// "minimum_height": 68*254,
  //
	// // A-list features
	// // "minimum_attractiveness" : 8000, // 4000 | 6000 | 8000 | 10000
	// // "maximum_attractiveness" : 8000, // 4000 | 6000 | 8000 | 10000
	// "bodytype": ["thin", "fit", "average"],
  //  // "thin" | "fit" | "average" | "jacked" | "overweight" | "a_little_extra" | "full_figured" | "curvy"
  //
	// // Background filter
	// // "languages": 0,
	// "speaks_my_language": true,
	// // "ethnicity": [], "asian" | "black" | "native_american" | ...
	// // "religion": ["agnosticism", "atheism"], "buddhism" | "catholicism" | "christianity" | "sikh" | ...
  //
	// // Availabilty filter
	// "availability": "single", // "not_single"
	// "monogamy": "yes", // "no"
	// "looking_for": ["short_term_dating", "new_friends", "long_term_dating"], // "new_friends" | "long_term_dating" | "casual_sex"
  //
	// // Personality filter
	// // "personality_filters": {
	// // 	"self_confidence" : ..., // "more" | "less"
	// // 	"compassion" : ..., // "more" | "less"
	// // 	"independence" : ..., // "more" | "less"
	// // 	"introversion" : ..., // "more" | "less"
	// // 	"adventuresome" : ..., // "more" | "less"
	// // 	"artsiness" : ..., // "more" | "less"
	// // 	"romantic" : ..., // "more" | "less"
	// // 	"sex_experience" : ..., // "more" | "less"
	// // 	"old_fashionedness" : ..., // "more" | "less"
	// // 	"trust_in_others" : ..., // "more" | "less"
	// // 	"purity" : ... // "more" | "less"
	// // },
  //
	// // Vices filter
	// "smoking": ["no"], // "when_drinking" | "trying_to_quit" | "yes"
	// "drinking": ["socially", "rarely"], // "not_at_all" | "often" | desperately"
	// "drugs": ["never"], // "never" | "often"
  //
	// // // Questions filter
	// // "questions": [403], // question id collection, 403 is "Do you enjoy discussing politics?"
	// // "answers": [2], // 2 for "yes" to question 403
	// // // maps by index to answer in "answers" field
  //
	// // More filter
	// "interest_ids": [], // interests id
	// , // "two_year_college" | "college_university" | "high_school"
	// "children": ["wants_kids", "doesnt_have", "might_want"], // "might_want" | "doesnt_want" | "has_one_or_more"
	// // "cats": ["has"],
	// // "dogs": [], "has"

	// Additional metadata
   // max number of results
  // "fields": "userinfo,thumbs,percentages,likes,last_contacts,online" // additional data to be returned
  

function search(okc, query, count) {
  let peopleReached = 0;
  okc.search(query, function(err,res,body) {
    // console.log(body)
    body.data.forEach(function(user) {
      let userArray = [];
      userArray.push(user.userid);
      console.log(userArray);

      function likeUserArray (userArray) {
          userArray.forEach(user_id => {
                okc.like(user_id);
                console.log("Liked user.")
              });
        }
      function messageUserArray (userArray) {
          userArray.forEach(user_id => {
                okc.sendMessage(user_id, "Hello.");
                console.log("Messaged user.")
              });
        };
      likeUserArray(userArray);
      messageUserArray(userArray);
      peopleReached = peopleReached + 1
    });
    console.log(`You reached ${peopleReached} people.`);

    // get next page with "after" cursor
    var hash = body.paging.cursors.after;

    // check termination condtion, otherwise recurse
    if (hash != null && count <= 5) {
      // get the query with the next hash
      query.after = hash;
      // increase the count
      newCount = count + body.data.length;
      // recursively call the search function
      search(okc, query, newCount);
    };
  });
};
search(okc, base_query, 1);

});

```
Here's what I came up with. Does these filters work for you? If you change some of them, does it crash?

**Comment by xmclark** [comment] 2018-09-16 21:07
I made #40 with your sample code. I dropped that into a new okcupidjs example project. 

It runs for me. windows 10 x64. I think I just spammed some okcupid users...oh well. 🙃 

I have got it to crash in some cases so I wil try to fix those, then see what else I can find. Thanks for this! When we get the example working 100% of the time, we can merge that PR.

**Comment by xmclark** [comment] 2018-09-16 21:15
These inputs work for me. Are there specific filters that cause it to fail?

Is it possibly related to sending messages or liking users?

**Comment by inspectordanno** [comment] 2018-09-17 22:40
I don't think it's related to messaging or liking users. The filters that cause the error you detailed in _catch param error_ aren't always consistent, sometimes it is education (most likely because that was the one that I messed with the most), other times it is one of the other ones. 

Also, if you take the time to put those userIDs in the browser that come up with your filters, they do not always match the filter parameters. For example, you could search for people who were only in college and graduate school, and it would return someone who didn't have any education listed. So I'm not sure if the filters are really working correctly.

**Comment by xmclark** [comment] 2018-09-22 17:00
> Also, if you go on OKC and look up some of the userIDs that are returned by the filters, they do not always match the filter parameters.

This has been my experience as well. It's kind of like the OKC web API was not meant for data scraping 🙃 

> It was just an experiment for me that actually ended up turning into a very fulfilling relationship

Same here! Happy for you man!

**Closed** 2018-12-09 08:03 UTC
